name: UMS_CI

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  build_ums:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.MY_APP_KEY }}
        APP_NAME: ${{ 'ums02' }}
      run: |
        docker build -t ums2 .
        docker tag ums2 registry.heroku.com/$APP_NAME/web
        docker login --username=_ --password=$MY_APP_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
